enable-magisk-update = true
parallel-jobs = 1
compression-level = 9

[YouTube]
build-mode = "module"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
excluded-patches = "'Bypass image region restrictions' 'Change start page' 'Custom Shorts action buttons' 'Custom double tap length' 'Disable QUIC protocol' 'Disable auto captions' 'Enable debug logging' 'Force player buttons background' 'Layout switch' 'Return YouTube Dislike' 'Spoof app version' 'Swipe controls' 'Translations' 'Restore old seekbar thumbnails'"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'MaterialYou'"
patcher-args = "-OpackageNameYouTube=app.rvx.android.youtube -OpackageNameYouTubeMusic=app.rvx.android.youtube.music -OcheckGmsCore=true -OgmsCoreVendorGroupId=app.revanced -OappIcon=MMT -OchangeSplashIcon=false -OrestoreOldSplashAnimation=true -OappName=YouTube "
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
riplib = true