enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Hide Shorts dimming' 'MaterialYou' 'Theme'"
excluded-patches = "'Bypass image region restrictions' 'Change start page' 'Custom Shorts action buttons' 'Custom double tap length' 'Disable QUIC protocol' 'Disable auto captions' 'Enable debug logging' 'Force player buttons background' 'Layout switch' 'Return YouTube Dislike' 'Spoof app version' 'Swipe controls' 'Translations'"

[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
build-mode = "both"
included-patches = "'Predictive back gesture'"
excluded-patches = "'Hide recommended users'"