enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "YT-Advanced ReVanced"
build-mode = "both"
included-patches = "'Hide voice search button' 'MaterialYou'"
excluded-patches = "'Change player flyout panel toggles' 'Alternative thumbnails' 'Append time stamps information' 'Change start page' 'Custom branding heading' 'Custom double tap length' 'Custom package name' 'Custom playback speed' 'Custom player overlay opacity' 'Default playback speed' 'Disable HDR video' 'Disable QUIC protocol' 'Disable auto captions' 'Disable haptic feedback' 'Disable rolling number animations' 'Disable speed overlay' 'Enable compact controls overlay' 'Enable language switch' 'Enable song search' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Force fullscreen' 'Hide captions button' 'Hide channel avatar section' 'Hide fullscreen panels' 'Hide latest videos button' 'Hide mix playlists' 'Hide seekbar' 'Hide time stamp' 'Layout switch' 'Return YouTube Dislike' 'Spoof device dimensions' 'Swipe controls' 'Translations'"
